-- CRIANDO VIEW E DANDO SELECT CONVERTENDO A DATA
CREATE VIEW VW_Consultas    as
SELECT  C.CODP              as COD_PACIENTE, 
        P.NOMEP             as PACIENTE, 
        C.CODM              as COD_MEDICO, 
        M.NOMEM             as MEDICO,
        M.ESPECIALIDADE     as ESPECIALIDADE,
        C.HORA              as HORA,
        convert(char(10), C.DATA, 103) as DATA_CONSULTA
FROM    CONSULTAS           as C
INNER JOIN PACIENTES        as P
ON C.CODP = P.CODP
INNER JOIN MEDICOS          as M
ON C.CODM = M.CODM


-- SELECIONANDO TODA VIEW
SELECT * FROM VW_Consultas


--  DELETANDO VIEW
DROP VIEW VW_Consultas


-- SELECIONANDO MEDICO, CONSULTAS DE MAIO A PARTIR DE 16H
SELECT  MEDICO,
        DATA_CONSULTA,
        HORA 
FROM    VW_Consultas
WHERE   HORA >= 16 and DATA_CONSULTA like '%/05/%'
  

-- SELECT NA VIEW CW_Consultas
SELECT  MEDICO 
FROM    VW_Consultas 
WHERE   MEDICO like 'M%'


-- UPDATE NA TABELA MÉDICOS    
UPDATE  VW_Consultas
SET     MEDICO = 'Marion'
WHERE   COD_MEDICO = 'M1' 


-- CRIANDO VIEW PARA SELECT DO CODIGO E NOME DO PACIENTE
CREATE      VIEW  VW_DadosPac as
SELECT      CODP, 
            NOMEP 
FROM        PACIENTES
WHERE       NOMEP like 'M%'

SELECT * FROM VW_DadosPac



-- CRIANDO VIEW PARA 20% DE DESCONTO NOS PRODUTOS DO BANCO SERRA
CREATE  VIEW VW_SERRA as 
SELECT  PRO_CODIGO,
        PRO_NOME,
        PRO_PRECO_VAREJO,
        PRO_PRECO_VAREJO * 0.8 AS PROMOCAO
FROM PRODUTOS

SELECT * FROM VW_SERRA


-- CRIANDO VIEW PARA EXIBIR TIPO DE PESSOA, O NÚMERO E NOME, QUANDO COMEÇAR COM 'ES'
CREATE  VIEW VW_PESSOA  as
SELECT  CAD_TIPO_PESSOA as TIPO_PESSOA,
        CAD_CNPJ        as 'CPF/CNPJ',
        CAD_NOME        as NOME
FROM    CADASTROS
WHERE   CAD_CNPJ is not null
UNION
SELECT  CAD_TIPO_PESSOA,
        CAD_CPF,
        CAD_NOME
FROM    CADASTROS
WHERE   CAD_CPF is not null

SELECT * FROM VW_PESSOA
WHERE NOME like 'Es%'
ORDER BY NOME


